---
- hosts: webservers
  become: yes
  tasks:
  - name: install webserver on ansible nodes
    apt: 
     name: apache2
     state: present
    when: ansible_os_family== "Debian"

  - name: start webserver on ansible nodes 
    service:
      name: apache2
      state: started
    when: ansible_os_family== "Debian"


  - name: install webserver on redhatansible nodes
    yum:
      name: httpd
      state: present
    when: ansible_os_family== "Redhat"

  