---
- hosts: 172.31.7.187
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myfristtaskresult

  - name: i want to execute linux command
    command: pwd
    register: presentworkingdirectory

  - name: i want to display presentworkingdirectory 
    debug: 
      msg: "{{presentworkingdirectory}}"
      
  - name: i want to disply fristtaskresult
    debug: 
      msg: "{{myfristtaskresult}}"