---
- hosts: 172.31.7.187
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myfristtaskresult

  - name: i want to execute linux command
    command: pwd
    register: presentworkingdirectory

  - name: i want to display presentworkingdirectory 
    debug: 
      msg: "{{presentworkingdirectory}}"

  - name: i want to disply fristtaskresult
    debug: 
      msg: "{{myfristtaskresult}}"

  - name: i want to execute linux command
    command: date
    register: todaydate

  - name: i want to display todaydate
    debug:
      msg: "{{todaydate}}"

  - name: i want to execute linux command
    command: whoami
    register: ansar

  - name: i want disply ansar
    debug: 
      msg: "{{ansar}}"

  - name: i want to execute linux command
    command: java -version
    register: java

  - name: i want to disply java 
    debug: 

     msg: "{{java}}"