---
- hosts: webservers
  become: yes
  tasks:
  - name: install git
    apt: 
      name: git 
      state: present

  - name: install tree
    apt: 
      name: tree
      state: presentt
  
  - name: ibnstall tree
    apt:
      name: tree
      state: present