---
- hosts: 172.31.6.191
  become: yes
  tasks:
  - include_tasks: myfile.yml 
  - name: i want to copy statis files into ansible nodes
    copy:
      src: mystaticfile
      dest: /home/ubuntu/statisfile

  - name: i want to install webserver
    apt:
      name: apache2
      state: present
  
  - name: copy dynamic files into ansible nodes
    template: 
      src: myindex.j2
      dest: /var/www/html/index.html