--- 
- hosts: 172.31.7.197
  become: yes
  tasks:
  - name: install git 
    apt: 
      name: git
      state: present
    tags: mygit

  - name: install wget
    yum: 
     name: wget
     state: present
    tags: mywget

  - name: install tree
    apt:
      name: tree
      state: present
    tags: mytree